"""Batch 2 zh_TW translations (auto-generated by Codex; merged into zh_TW.py)."""

BATCH_2 = {
    "manage_animation": {
        "description": (
            "管理 Unity 動畫：控制 Animator 並建立 AnimationClip。"
            "動作前綴：animator_*（play、crossfade、設定參數、取得資訊）、"
            "controller_*（建立 AnimatorController、新增狀態/轉場/參數）、"
            "clip_*（建立 clip、新增 keyframe curve、指派給 GameObject）。"
            "動作專用參數放在 `properties`（key 與 ManageAnimation.cs 相同）。"
        ),
        "title": "管理 Animation",
        "params": {
            "action": "執行的動作（前綴：animator_、controller_、clip_）。",
            "target": "目標 GameObject（名稱/路徑/id）。",
            "search_method": "尋找目標 GameObject 的方式。",
            "clip_path": "AnimationClip 的 Asset 路徑（例如 'Assets/Animations/Walk.anim'）。",
            "controller_path": "AnimatorController 的 Asset 路徑（例如 'Assets/Animators/Player.controller'）。",
            "properties": "動作專用參數（dict 或 JSON 字串）。",
        },
    },
    "manage_camera": {
        "description": (
            "管理相機（Unity Camera + Cinemachine）。即使沒有 Cinemachine 也可使用基本 Camera；"
            "安裝 Cinemachine 時可啟用 preset、pipeline 與 blending。"
            "使用 ping 檢查 Cinemachine 是否可用。\n\n"
            "設定：\n"
            "- ping：檢查 Cinemachine 是否可用\n"
            "- ensure_brain：確保主相機上存在 CinemachineBrain\n"
            "- get_brain_status：取得 Brain 狀態（active camera、blend 等）\n\n"
            "建立相機：\n"
            "- create_camera：使用 preset 建立相機（third_person、freelook、follow、dolly、static、top_down、side_scroller）。"
            "沒有 Cinemachine 時退回基本 Camera。\n\n"
            "設定相機：\n"
            "- set_target：設定相機的 Follow 和/或 LookAt 目標\n"
            "- set_priority：設定 Brain 選取用的相機 priority\n"
            "- set_lens：設定 lens（fieldOfView、nearClipPlane、farClipPlane、orthographicSize、dutch）\n"
            "- set_body：設定 Body component（bodyType 用於替換，並可設定 component properties）\n"
            "- set_aim：設定 Aim component（aimType 用於替換，並可設定 component properties）\n"
            "- set_noise：設定 Noise component（amplitudeGain、frequencyGain）\n\n"
            "Extensions：\n"
            "- add_extension：新增 extension（extensionType：CinemachineConfiner2D、CinemachineDeoccluder、"
            "CinemachineImpulseListener、CinemachineFollowZoom、CinemachineRecomposer 等）\n"
            "- remove_extension：依 type 移除 extension\n\n"
            "控制相機：\n"
            "- set_blend：設定 default blend（style：Cut/EaseInOut/Linear 等、duration）\n"
            "- force_camera：覆蓋 Brain，改用指定相機\n"
            "- release_override：釋放 camera override\n"
            "- list_cameras：列出所有相機與狀態\n\n"
            "擷取：\n"
            "- screenshot：擷取 screenshot。預設（未指定 camera）使用 ScreenCapture API，"
            "會擷取所有 render layers，包含 Screen Space - Overlay UI canvases。"
            "指定 camera 時使用直接 Camera rendering，不包含 Screen Space - Overlay canvases"
            "（僅在需要無 UI 的特定視角時使用）。支援 include_image=true 回傳 inline base64 PNG、"
            "batch='surround' 產生 6 角度 contact sheet、batch='orbit' 產生可設定 grid、"
            "view_target/view_position 用於定位擷取，以及 capture_source='scene_view' 擷取目前作用中的 Unity Scene View 視窗。\n"
            "- screenshot_multiview：screenshot 的簡寫，使用 batch='surround' 且 include_image=true。"
        ),
        "title": "管理相機",
        "params": {
            "action": "執行的相機動作。",
            "target": "目標相機（名稱、路徑或 instance ID）。",
            "search_method": "尋找目標的方式。",
            "properties": "動作專用參數（dict 或 JSON 字串）。",
            "screenshot_file_name": "Screenshot 檔案名稱（選填）。預設為 timestamp。",
            "screenshot_super_size": "Screenshot supersize 倍率（integer >= 1）。",
            "camera": (
                "要擷取的 Camera（名稱、路徑或 instance ID）。省略時使用 ScreenCapture API"
                "（擷取所有圖層，包含 Screen Space Overlay UI）。只有在需要特定相機視角時才指定；"
                "注意：Camera 渲染的截圖不會出現 Screen Space - Overlay canvases。"
            ),
            "include_image": "若為 true，回傳 inline base64 PNG 截圖。預設 false。",
            "max_resolution": "inline image 的最大解析度（最長邊 px）。預設 640。",
            "capture_source": (
                "Screenshot 來源。'game_view'（預設）擷取遊戲/Camera 路徑；"
                "'scene_view' 擷取目前作用中的 Unity Scene View 視窗。"
            ),
            "batch": "批次擷取模式：'surround'（6 個角度）或 'orbit'（可設定 grid）。",
            "view_target": (
                "要聚焦的目標。GameObject 名稱/路徑/ID 或 [x,y,z]。"
                "game_view：讓 Camera 對準目標。scene_view：將 Scene View 框選到目標。"
            ),
            "view_position": "用於定位擷取的 Camera 世界座標 [x,y,z]。",
            "view_rotation": "Camera 的 Euler rotation [x,y,z]。若同時提供 view_target，會覆蓋 view_target。",
            "orbit_angles": "batch='orbit' 的方位角取樣數（預設 8，最大 36）。",
            "orbit_elevations": "batch='orbit' 的 elevation 角度（度數，預設 [0, 30, -15]）。",
            "orbit_distance": "batch='orbit' 時 Camera 與目標的距離（預設自動）。",
            "orbit_fov": "batch='orbit' 時 Camera FOV 度數（預設 60）。",
            "output_folder": (
                "Screenshot 輸出資料夾（選填）。可為專案相對路徑"
                "（例如 'Assets/Screenshots' 或 'Captures'）或專案內絕對路徑。"
                "會覆蓋使用者的 Editor 偏好設定。省略時依序使用 Editor 偏好設定，"
                "再退回內建預設（Assets/Screenshots）。"
            ),
        },
    },
    "manage_graphics": {
        "description": (
            "管理 rendering graphics：Volume、post-processing、light baking、rendering stats、pipeline settings，"
            "以及 URP Renderer features。使用 ping 檢查 pipeline 與可用 features。\n\n"
            "Volume（需要 URP/HDRP）：\n"
            "- volume_create、volume_add_effect、volume_set_effect、volume_remove_effect\n"
            "- volume_get_info、volume_set_properties、volume_list_effects、volume_create_profile\n\n"
            "Bake（僅 Edit mode）：\n"
            "- bake_start、bake_cancel、bake_status、bake_clear、bake_reflection_probe\n"
            "- bake_get_settings、bake_set_settings\n"
            "- bake_create_light_probe_group、bake_create_reflection_probe、bake_set_probe_positions\n\n"
            "Stats：\n"
            "- stats_get：Renderer counters（draw calls、batches、triangles 等）\n"
            "- stats_list_counters、stats_set_scene_debug、stats_get_memory\n\n"
            "Pipeline：\n"
            "- pipeline_get_info、pipeline_set_quality、pipeline_get_settings、pipeline_set_settings\n\n"
            "Features（僅 URP）：\n"
            "- feature_list、feature_add、feature_remove、feature_configure、feature_toggle、feature_reorder\n\n"
            "Skybox / Environment：\n"
            "- skybox_get：讀取所有 environment settings（material、ambient、fog、reflection、sun）\n"
            "- skybox_set_material：依 Asset 路徑設定 skybox material\n"
            "- skybox_set_properties：設定目前 skybox material 的 properties（tint、exposure、rotation）\n"
            "- skybox_set_ambient：設定 ambient lighting 模式與色彩\n"
            "- skybox_set_fog：啟用/設定 fog（mode、color、density、start/end distance）\n"
            "- skybox_set_reflection：設定 environment reflection settings\n"
            "- skybox_set_sun：設定 sun source light"
        ),
        "title": "管理圖形",
        "params": {
            "action": "執行的圖形動作。",
            "target": "目標物件名稱或 instance ID。",
            "effect": "效果類型名稱（例如 'Bloom'、'Vignette'）。",
            "parameters": "參數值 dict。",
            "properties": "要設定的屬性 dict。",
            "settings": "設定 dict（bake/pipeline）。",
            "name": "建立物件時使用的名稱。",
            "is_global": "Volume 是否為 global（預設 true）。",
            "weight": "Volume 權重（0-1）。",
            "priority": "Volume 優先權。",
            "profile_path": "VolumeProfile 的 Asset 路徑。",
            "effects": "volume_create 的效果定義。",
            "path": "volume_create_profile 的 Asset 路徑。",
            "level": "Quality level 名稱或索引。",
            "position": "位置 [x,y,z]。",
            "grid_size": "Probe grid 大小 [x,y,z]。",
            "spacing": "Probe grid 間距。",
            "size": "Probe/Volume 大小 [x,y,z]。",
            "resolution": "Probe 解析度。",
            "mode": "Probe 模式或 debug 模式。",
            "hdr": "Reflection probe 的 HDR。",
            "box_projection": "Reflection probe 的 box projection。",
            "positions": "Probe 位置陣列。",
            "index": "Feature 索引。",
            "active": "Feature 啟用狀態。",
            "order": "Feature 重新排序索引。",
            "async_bake": "非同步 bake（預設 true）。",
            "feature_type": "Renderer feature 類型名稱。",
            "material": "Feature 的 Material Asset 路徑。",
            "color": "Ambient/fog 的色彩 [r,g,b,a]。",
            "intensity": "強度值（ambient/reflection）。",
            "ambient_mode": "Ambient 模式：Skybox、Trilight、Flat、Custom。",
            "equator_color": "Equator 色彩 [r,g,b,a]（Trilight 模式）。",
            "ground_color": "Ground 色彩 [r,g,b,a]（Trilight 模式）。",
            "fog_enabled": "啟用或停用 fog。",
            "fog_mode": "Fog 模式：Linear、Exponential、ExponentialSquared。",
            "fog_color": "Fog 色彩 [r,g,b,a]。",
            "fog_density": "Fog 密度（Exponential 模式）。",
            "fog_start": "Fog 起始距離（Linear 模式）。",
            "fog_end": "Fog 結束距離（Linear 模式）。",
            "bounces": "Reflection bounces。",
            "reflection_mode": "預設 reflection 模式：Skybox、Custom。",
        },
    },
    "manage_physics": {
        "description": (
            "管理物理設定、collision matrix、Physics Material、Joint、queries 與 validation。\n\n"
            "Settings：ping、get_settings、set_settings\n"
            "Collision Matrix：get_collision_matrix、set_collision_matrix\n"
            "Materials：create_physics_material、configure_physics_material、assign_physics_material\n"
            "Joints：add_joint、configure_joint、remove_joint\n"
            "Queries：raycast、raycast_all、linecast、shapecast、overlap\n"
            "Forces：apply_force\n"
            "Rigidbody：get_rigidbody、configure_rigidbody\n"
            "Validation：validate\n"
            "Simulation：simulate_step\n"
        ),
        "title": "管理 Physics",
        "params": {
            "action": "執行的物理動作。",
            "dimension": "Physics 維度：'3d'（預設）或 '2d'。",
            "settings": "set_settings 使用的 key-value 設定。",
            "layer_a": "collision matrix 的 Layer 名稱或索引。",
            "layer_b": "collision matrix 的 Layer 名稱或索引。",
            "collide": "Layer 是否應碰撞（set_collision_matrix）。",
            "name": "新 Physics Material 的名稱。",
            "path": "Material 的 Asset 路徑。",
            "dynamic_friction": "Dynamic friction（0-1）。",
            "static_friction": "Static friction（0-1）。",
            "bounciness": "Bounciness（0-1）。",
            "friction": "2D Material 的 friction。",
            "friction_combine": "Friction combine 模式：Average、Minimum、Multiply、Maximum。",
            "bounce_combine": "Bounce combine 模式：Average、Minimum、Multiply、Maximum。",
            "material_path": "assign 用 Physics Material Asset 的路徑。",
            "target": "目標 GameObject 名稱或 instance ID。",
            "collider_type": "要鎖定的特定 Collider 類型。",
            "search_method": "解析目標時使用的搜尋方式。",
            "joint_type": (
                "Joint 類型：fixed、hinge、spring、character、configurable（3D）；"
                "distance、fixed、friction、hinge、relative、slider、spring、target、wheel（2D）。"
            ),
            "connected_body": "Joint 的 connected body 目標。",
            "motor": "Motor 設定：{targetVelocity, force, freeSpin}。",
            "limits": "Limits 設定：{min, max, bounciness}。",
            "spring": "Spring 設定：{spring, damper, targetPosition}。",
            "drive": "ConfigurableJoint 的 drive 設定。",
            "properties": "Joint 或 Material 的直接屬性 dict。",
            "origin": "Ray 原點 [x,y,z] 或 [x,y]。",
            "direction": "Ray 方向 [x,y,z] 或 [x,y]。",
            "max_distance": "Raycast 最大距離。",
            "layer_mask": "Query 的 Layer mask（名稱或 int）。",
            "query_trigger_interaction": "Trigger interaction：UseGlobal、Ignore、Collide。",
            "shape": "Overlap 形狀：sphere、box、capsule（3D）；circle、box、capsule（2D）。",
            "position": "Overlap 位置 [x,y,z] 或 [x,y]。",
            "size": "Overlap 大小：float（radius）或 [x,y,z]（half-extents）。",
            "start": "Linecast 起點 [x,y,z] 或 [x,y]。",
            "end": "Linecast 終點 [x,y,z] 或 [x,y]。",
            "point1": "Capsule shapecast point1 [x,y,z]。",
            "point2": "Capsule shapecast point2 [x,y,z]。",
            "height": "Shapecast 的 capsule 高度。",
            "capsule_direction": "Capsule 方向：0=X、1=Y（預設）、2=Z。",
            "angle": "2D shape casts 的旋轉角度。",
            "force": "apply_force 的力向量 [x,y,z] 或 [x,y]。",
            "force_mode": "Force mode：Force、Impulse、Acceleration、VelocityChange（3D）；Force、Impulse（2D）。",
            "force_type": "Force type：'normal'（預設）或 'explosion'（僅 3D）。",
            "torque": "Torque 向量 [x,y,z]（3D）或 [z]（2D）。",
            "explosion_position": "Explosion 中心 [x,y,z]。",
            "explosion_radius": "Explosion 半徑。",
            "explosion_force": "Explosion 力量大小。",
            "upwards_modifier": "Explosion 向上修正值。",
            "steps": "模擬步數（最大 100）。",
            "step_size": "每步秒數。",
            "page_size": "validate 結果的頁面大小（預設 50）。",
            "cursor": "validate 分頁的 cursor offset。",
            "component_index": (
                "當存在多個相同類型 Component 時，用於選擇第幾個的 zero-based 索引"
                "（例如多個 HingeJoint 或 BoxCollider）。省略時使用第一個 instance。"
            ),
        },
    },
    "manage_profiler": {
        "description": (
            "控制 Unity Profiler session、讀取 counter、memory snapshot 與 Frame Debugger。\n\n"
            "Session：\n"
            "- profiler_start：啟用 Profiler，並可選擇錄製到 .raw 檔案（log_file、enable_callstacks）\n"
            "- profiler_stop：停用 Profiler，停止錄製\n"
            "- profiler_status：取得啟用狀態、active areas、recording path\n"
            "- profiler_set_areas：切換 ProfilerAreas 開/關（areas dict）\n\n"
            "Counters：\n"
            "- get_frame_timing：FrameTimingManager data（12 fields，同步）\n"
            "- get_counters：依 category + 可選 counter names 讀取 generic counter（async，等待 1 frame）\n"
            "- get_object_memory：依 path 取得特定物件的 memory size\n\n"
            "Memory Snapshot（需要 com.unity.memoryprofiler）：\n"
            "- memory_take_snapshot：擷取 memory snapshot 到檔案\n"
            "- memory_list_snapshots：列出可用的 .snap 檔案\n"
            "- memory_compare_snapshots：比較兩個 snapshot 檔案\n\n"
            "Frame Debugger：\n"
            "- frame_debugger_enable：啟用 Frame Debugger，回報 event count\n"
            "- frame_debugger_disable：停用 Frame Debugger\n"
            "- frame_debugger_get_events：取得 draw call events（分頁，透過 reflection 盡力處理）"
        ),
        "title": "管理 Profiler",
        "params": {
            "action": "執行的 Profiler 動作。",
            "category": "get_counters 的 Profiler category 名稱（例如 Render、Scripts、Memory、Physics）。",
            "counters": "get_counters 的特定 counter 名稱。省略時讀取 category 中全部。",
            "object_path": "get_object_memory 的 Scene hierarchy 或 Asset 路徑。",
            "log_file": "profiler_start 錄製用 .raw 檔案路徑。",
            "enable_callstacks": "啟用 profiler_start 的 allocation callstacks。",
            "areas": "profiler_set_areas 使用的 area name 到 bool 的 dict。",
            "snapshot_path": "memory_take_snapshot 的輸出路徑。",
            "search_path": "memory_list_snapshots 的搜尋資料夾。",
            "snapshot_a": "memory_compare_snapshots 的第一個 snapshot 路徑。",
            "snapshot_b": "memory_compare_snapshots 的第二個 snapshot 路徑。",
            "page_size": "frame_debugger_get_events 的頁面大小（預設 50）。",
            "cursor": "frame_debugger_get_events 的 cursor offset。",
        },
    },
    "manage_build": {
        "description": (
            "管理 Unity player build：觸發 build、切換平台、設定 settings、"
            "管理 build scenes 與 profiles、跨平台執行 batch builds。"
            "動作：build、status、platform、settings、scenes、profiles、batch、cancel。"
        ),
        "title": "管理建置",
        "params": {
            "action": "動作：build、status、platform、settings、scenes、profiles、batch、cancel",
            "target": "Build target：windows64、osx、linux64、android、ios、webgl、uwp、tvos、visionos",
            "output_path": "Build 輸出路徑。",
            "scenes": "Scene 路徑的 JSON array，或以逗號分隔的路徑。",
            "development": "Development build（true/false）。",
            "options": (
                "BuildOptions 的 JSON array：clean_build、auto_run、deep_profiling、"
                "compress_lz4、strict_mode、detailed_report。"
            ),
            "subtarget": "Build subtarget：player 或 server。",
            "scripting_backend": "Scripting backend：mono 或 il2cpp（持久變更）。",
            "profile": "Build Profile Asset 路徑（僅 Unity 6+）。",
            "property": (
                "Settings 屬性：product_name、company_name、version、bundle_id、"
                "scripting_backend、defines、architecture。"
            ),
            "value": "要設定給 property 的值（省略時讀取）。",
            "activate": "啟用 build profile（true/false）。",
            "targets": "batch build 的 target JSON array。",
            "profiles": "batch build 的 profile 路徑 JSON array（Unity 6+）。",
            "output_dir": "batch build 的基底輸出資料夾。",
            "job_id": "status/cancel 的 Job ID。",
        },
    },
    "manage_packages": {
        "description": (
            "管理 Unity Package：查詢、安裝、移除、embed，以及設定 registries。\n\n"
            "查詢（唯讀）：\n"
            "- list_packages：列出所有已安裝 Package\n"
            "- search_packages：以 keyword 搜尋 Unity registry\n"
            "- get_package_info：取得特定已安裝 Package 的詳細資訊\n"
            "- ping：檢查 package manager 是否可用\n"
            "- status：輪詢 async job status（list/search 需要 job_id；add/remove/embed 可選）\n\n"
            "安裝/移除：\n"
            "- add_package：安裝 Package（name、name@version、git URL 或 file: path）\n"
            "- remove_package：移除 Package（檢查 dependents；使用 force=true 覆蓋）\n\n"
            "Registries：\n"
            "- list_registries：列出所有 scoped registries\n"
            "- add_registry：新增 scoped registry（例如 OpenUPM）\n"
            "- remove_registry：移除 scoped registry\n\n"
            "Utility：\n"
            "- embed_package：複製 Package 到本機 Packages/ 以便編輯\n"
            "- resolve_packages：強制重新解析所有 Package"
        ),
        "title": "管理 Package",
        "params": {
            "action": "執行的 Package 動作。",
            "package": "Package identifier（name、name@version、git URL 或 file: path）。",
            "force": "即使其他 Package 相依於它，也強制移除。",
            "query": "search_packages 的搜尋 query。",
            "job_id": "輪詢 status 的 Job ID。",
            "name": "add_registry/remove_registry 的 registry 名稱。",
            "url": "add_registry 的 registry URL。",
            "scopes": "add_registry 的 registry scopes。",
        },
    },
    "manage_shader": {
        "description": (
            "管理 Unity 中的 Shader script（create、read、update、delete）。"
            "唯讀動作：read。修改型動作：create、update、delete。"
        ),
        "title": "管理 Shader",
        "params": {
            "action": "對 Shader script 執行 CRUD 操作。",
            "name": "Shader 名稱（不含 .cs 副檔名）。",
            "path": "Asset 路徑（預設：\"Assets/\"）。",
            "contents": "create/update 的 Shader 程式碼。",
        },
    },
    "manage_texture": {
        "description": (
            "為 Unity 進行程序化 Texture 產生。建立 solid fill、patterns"
            "（checkerboard、stripes、dots、grid、brick）、gradients 與 noise 的 Texture。"
            "動作：create、modify、delete、create_sprite、apply_pattern、apply_gradient、apply_noise、set_import_settings。"
        ),
        "title": "管理 Texture",
        "params": {
            "action": "執行的動作。",
            "path": "輸出 Texture 路徑（例如 'Assets/Textures/MyTexture.png'）。",
            "width": "Texture 寬度，單位 pixels（預設：64）。",
            "height": "Texture 高度，單位 pixels（預設：64）。",
            "fill_color": (
                "填色，格式為 [r, g, b] 或 [r, g, b, a] array、{r, g, b, a} object，或 hex string。"
                "接受 0-255 範圍（例如 [255, 0, 0]）或 0.0-1.0 normalized 範圍（例如 [1.0, 0, 0]）。"
            ),
            "pattern": "apply_pattern 動作的 pattern 類型。",
            "palette": "色盤，格式為 [[r,g,b,a], ...]。接受 0-255 範圍或 0.0-1.0 normalized 範圍。",
            "pattern_size": "Pattern cell 大小，單位 pixels（預設：8）。",
            "pixels": "Pixel data，格式為 [r,g,b,a] 值的 JSON array 或 base64 string。",
            "image_path": "create/create_sprite 的來源圖片檔案路徑（PNG/JPG）。",
            "gradient_type": "Gradient 類型（預設：linear）。",
            "gradient_angle": "Linear gradient 的角度，單位 degrees（預設：0）。",
            "noise_scale": "Noise scale/frequency（預設：0.1）。",
            "octaves": "Noise detail 的 octaves 數量（預設：1）。",
            "set_pixels": "要修改的區域：{x, y, width, height, color or pixels}。",
            "as_sprite": "設定為 Sprite：{pivot: [x,y], pixels_per_unit: 100}，或 true 使用預設值。",
            "import_settings": (
                "TextureImporter settings dict。Keys：texture_type (default/normal_map/sprite/etc)、"
                "texture_shape (2d/cube)、srgb (bool)、alpha_source (none/from_input/from_gray_scale)、"
                "alpha_is_transparency (bool)、readable (bool)、generate_mipmaps (bool)、"
                "wrap_mode/wrap_mode_u/wrap_mode_v (repeat/clamp/mirror/mirror_once)、"
                "filter_mode (point/bilinear/trilinear)、aniso_level (0-16)、max_texture_size (32-16384)、"
                "compression (none/low_quality/normal_quality/high_quality)、compression_quality (0-100)、"
                "sprite_mode (single/multiple/polygon)、sprite_pixels_per_unit、sprite_pivot、"
                "sprite_mesh_type (full_rect/tight)、sprite_extrude (0-32)。"
            ),
        },
    },
    "manage_ui": {
        "description": (
            "管理 Unity UI Toolkit 元素（UXML 檔案、USS stylesheets、UIDocument components）。"
            "唯讀動作：ping、read、get_visual_tree、list。"
            "修改型動作：create、update、delete、attach_ui_document、detach_ui_document、"
            "create_panel_settings、update_panel_settings、modify_visual_element。\n"
            "視覺動作：render_ui（將 UI panel 擷取為 PNG screenshot 以便自我評估）。\n"
            "結構動作：link_stylesheet（將 Style src reference 新增到 UXML 檔案）。\n\n"
            "UI Toolkit workflow：\n"
            "1. 使用 list 探索既有 UI assets\n"
            "2. 建立 UXML 檔案（結構，類似 HTML）\n"
            "3. 建立 USS 檔案（樣式，類似 CSS）\n"
            "4. 透過 link_stylesheet 將 stylesheet 連結到 UXML\n"
            "5. 將 UIDocument 附加到 GameObject，並指定 UXML source\n"
            "6. 使用 get_visual_tree 檢查結果\n"
            "7. 使用 modify_visual_element 修改 live elements 的 text、classes 或 inline styles\n"
            "8. 使用 render_ui 擷取視覺預覽以便自我評估\n"
            "   - Play mode：第一次呼叫會排入 WaitForEndOfFrame screen capture 並回傳 pending=true；\n"
            "     第二次呼叫 render_ui 以取回已儲存的 PNG（hasContent 會是 true）。\n"
            "   - Editor mode：將 RenderTexture 指派給 PanelSettings（盡力處理；可能仍為空白）。\n"
            "9. 使用 detach_ui_document 從 GameObject 移除 UIDocument\n"
            "10. 使用 delete 移除 .uxml/.uss 檔案\n\n"
            "重要：在 UXML 中一律使用 <ui:Style>（含 ui: namespace prefix），不要使用裸 <Style>。"
            "使用沒有 prefix 的 <Style> 會使 UI Builder 無法開啟檔案。"
        ),
        "title": "管理 UI",
        "params": {
            "action": "執行的動作。",
            "path": (
                "Assets 相對路徑（例如 'Assets/UI/MainMenu.uxml' 或 'Assets/UI/Styles.uss'）。"
                "render_ui：可選的 UXML 路徑，可不透過 Scene GameObject 直接 render。"
            ),
            "contents": "檔案內容（UXML 或 USS markup）。純文字，會自動處理 encoding。",
            "target": "attach_ui_document / get_visual_tree / render_ui 的目標 GameObject 名稱或路徑。",
            "source_asset": "UXML VisualTreeAsset 路徑（例如 'Assets/UI/MainMenu.uxml'）。",
            "panel_settings": "PanelSettings Asset 路徑。省略時自動建立預設值。",
            "sort_order": "UIDocument sort order（預設 0）。",
            "scale_mode": "Panel scale mode。舊版 shorthand；建議改用 'settings' dict。",
            "reference_resolution": "Reference resolution，格式為 {width, height}。舊版 shorthand；建議改用 'settings' dict。",
            "settings": (
                "create_panel_settings 的通用 PanelSettings properties dict。Keys："
                "scaleMode (ConstantPixelSize|ConstantPhysicalSize|ScaleWithScreenSize)、"
                "referenceResolution ({width,height})、screenMatchMode (MatchWidthOrHeight|ShrinkToFit|ExpandToFill)、"
                "match (0-1 float)、referenceDpi、fallbackDpi、sortingOrder、targetDisplay、"
                "clearColor (bool)、colorClearValue (#RRGGBB or {r,g,b,a})、clearDepthStencil、"
                "themeStyleSheet (asset path)、dynamicAtlasSettings ({minAtlasSize,maxAtlasSize,maxSubTextureSize,activeFilters})。"
            ),
            "max_depth": "遍歷 visual tree 的最大深度（預設 10）。",
            "width": "render_ui 的 render 寬度，單位 pixels（預設 1920）。",
            "height": "render_ui 的 render 高度，單位 pixels（預設 1080）。",
            "include_image": "在 response 中回傳 inline base64 PNG（預設 false）。render_ui 使用。",
            "max_resolution": "inline base64 image 的最大解析度（預設 640）。render_ui 使用。",
            "screenshot_file_name": "Render 輸出的自訂檔案名稱（預設：自動產生）。render_ui 使用。",
            "output_folder": (
                "Render 輸出資料夾（選填）。可為專案相對路徑"
                "（例如 'Assets/Screenshots' 或 'Captures'）或專案內絕對路徑。"
                "會覆蓋使用者的 Editor 偏好設定。省略時依序使用 Editor 偏好設定，"
                "再退回內建預設（Assets/Screenshots）。render_ui 使用。"
            ),
            "stylesheet": "要連結的 USS stylesheet 路徑（例如 'Assets/UI/Styles.uss'）。link_stylesheet 使用。",
            "filter_type": "依類型篩選 UI Asset：'uxml'、'uss'、'PanelSettings'，或省略以取得全部。list 使用。",
            "page_size": "每頁結果數量（預設 50）。list 使用。",
            "page_number": "頁碼，1-based（預設 1）。list 使用。",
            "element_name": "要修改的 visual element 名稱（UXML 中的 'name' attribute）。modify_visual_element 使用。",
            "text": "Label/Button 元素的新文字內容。modify_visual_element 使用。",
            "add_classes": "要新增到元素的 USS class 名稱。modify_visual_element 使用。",
            "remove_classes": "要從元素移除的 USS class 名稱。modify_visual_element 使用。",
            "toggle_classes": "要在元素上切換的 USS class 名稱。modify_visual_element 使用。",
            "style": "要設定的 inline styles（例如 {'backgroundColor': '#FF0000', 'fontSize': 24}）。modify_visual_element 使用。",
            "enabled": "設定元素啟用/停用狀態。modify_visual_element 使用。",
            "visible": "設定元素可見性（display: flex/none）。modify_visual_element 使用。",
            "tooltip": "設定元素 tooltip 文字。modify_visual_element 使用。",
        },
    },
}
