"""Batch 3 zh_TW translations (auto-generated by Codex; merged into zh_TW.py)."""

BATCH_3 = {
    "manage_vfx": {
        "description": (
            "管理 Unity VFX Component（ParticleSystem、VisualEffect、LineRenderer、TrailRenderer）。"
            "動作前綴：particle_*、vfx_*、line_*、trail_*。"
            "動作專用參數放在 `properties`（key 與 ManageVFX.cs 相符）。"
        ),
        "title": "管理 VFX",
        "params": {
            "action": "要執行的動作（前綴：particle_、vfx_、line_、trail_）。",
            "target": "目標 GameObject（名稱/路徑/id）。",
            "search_method": "如何尋找目標 GameObject。",
            "properties": "動作專用參數（dict 或 JSON 字串）。",
            "component_index": (
                "以 0 為起點的索引，用來在存在多個同類型 Component 時選取哪一個"
                "（例如多個 ParticleSystem）。若省略，會以第一個 instance 為目標。"
            ),
        },
    },
    "manage_probuilder": {
        "description": (
            "管理用於 Editor 內 3D 建模的 ProBuilder mesh。"
            "需要 com.unity.probuilder package。\n\n"
            "形狀建立：\n"
            "- create_shape：建立 ProBuilder primitive（shape_type: Cube/Cylinder/Sphere/Plane/Cone/"
            "Torus/Pipe/Arch/Stair/CurvedStair/Door/Prism）。形狀專用參數放在 properties "
            "（size, radius, height, depth, width, segments, rows, columns, innerRadius, outerRadius 等）。\n"
            "- create_poly_shape：從 2D polygon footprint 建立 mesh（points: [[x,y,z],...], "
            "extrudeHeight, flipNormals）。\n\n"
            "mesh 編輯：\n"
            "- extrude_faces：向外擠出 faces（faceIndices, distance, method: FaceNormal/VertexNormal/IndividualFaces）。\n"
            "- extrude_edges：擠出 edges（edgeIndices 或 edges [{a,b},...], distance, asGroup）。\n"
            "- bevel_edges：倒角 edges（edgeIndices 或 edges [{a,b},...], amount 0-1）。\n"
            "- subdivide：細分 faces（faceIndices 可選；省略時套用全部）。\n"
            "- delete_faces：刪除 faces（faceIndices）。\n"
            "- bridge_edges：橋接兩條 open edges（edgeA, edgeB 為 {a,b} pair, allowNonManifold）。\n"
            "- connect_elements：連接 edges 或 faces（edgeIndices/edges 或 faceIndices）。\n"
            "- detach_faces：分離 faces（faceIndices, deleteSourceFaces: bool）。\n"
            "- flip_normals：翻轉 face normals（faceIndices）。\n"
            "- merge_faces：將 faces 合併成一個（faceIndices）。\n"
            "- combine_meshes：合併多個 ProBuilder objects（targets: GameObject 清單）。\n"
            "- merge_objects：將 objects 合併為一個 ProBuilder mesh（targets 清單，自動轉換）。\n"
            "- duplicate_and_flip：建立雙面 geometry（faceIndices）。\n"
            "- create_polygon：將既有 vertices 連接成新的 face（vertexIndices, unordered）。\n\n"
            "vertex 操作：\n"
            "- merge_vertices：將 vertices 收合到單一點（vertexIndices, collapseToFirst）。\n"
            "- weld_vertices：焊接 proximity radius 內的 vertices（vertexIndices, radius）。\n"
            "- split_vertices：拆分共用 vertices（vertexIndices）。\n"
            "- move_vertices：平移 vertices（vertexIndices, offset [x,y,z]）。\n"
            "- insert_vertex：在 edge（{a,b}）或 face（faceIndex）上的 point [x,y,z] 插入 vertex。\n"
            "- append_vertices_to_edge：在 edges 上插入等距 points（edgeIndices/edges, count）。\n\n"
            "選取：\n"
            "- select_faces：依條件選取 faces（direction: up/down/forward/back/left/right, "
            "tolerance, growFrom, growAngle, floodFrom, floodAngle, loopFrom, ring）。"
            "回傳 faceIndices array，可供其他動作使用。\n\n"
            "UV 與 Material：\n"
            "- set_face_material：指派 Material 到 faces（faceIndices 可選；省略時套用所有 faces, materialPath）。\n"
            "- set_face_color：設定 faces 的 vertex color（faceIndices 可選；省略時套用所有 faces, color [r,g,b,a]）。\n"
            "- set_face_uvs：設定 UV auto-unwrap 參數（faceIndices 可選；省略時套用所有 faces, "
            "scale, offset, rotation, flipU, flipV）。\n\n"
            "查詢：\n"
            "- get_mesh_info：取得 ProBuilder mesh 詳細資訊。使用 include 參數控制詳細程度："
            "'summary'（預設：counts, bounds, materials）、'faces'（+ face normals/centers/directions）、"
            "'edges'（+ edge vertex pairs）、'all'（全部）。每個 face 都包含 direction "
            "（'top','bottom','front','back','left','right'），可供語意選取。\n"
            "- convert_to_probuilder：將標準 Unity mesh 轉換成 ProBuilder 以便編輯。\n\n"
            "平滑：\n"
            "- set_smoothing：設定 faces 的 smoothing group（faceIndices, smoothingGroup: 0=hard, 1+=smooth）。\n"
            "- auto_smooth：依角度自動指派 smoothing groups（angleThreshold: default 30）。\n\n"
            "mesh 工具：\n"
            "- center_pivot：將 pivot point 移到 mesh bounds center。\n"
            "- set_pivot：將 pivot 設到任意 world position（position [x,y,z]）。\n"
            "- freeze_transform：將 position/rotation/scale bake 到 vertex data，並重設 transform。\n"
            "- validate_mesh：檢查 mesh health（degenerate triangles, unused vertices）。唯讀。\n"
            "- repair_mesh：自動修復 degenerate triangles 與 unused vertices。\n\n"
            "工作流程提示：編輯前呼叫 get_mesh_info 並使用 include='faces'，查看 face normals 與 directions。"
            "每個 face 會顯示其 direction（'top','bottom','front','back','left','right'），"
            "讓你能為 extrude_faces 或 delete_faces 等操作挑選正確 indices。"
        ),
        "title": "管理 ProBuilder",
        "params": {
            "action": "要執行的動作。",
            "target": "目標 GameObject（名稱/路徑/id）。",
            "search_method": "如何尋找目標 GameObject。",
            "properties": "動作專用參數（dict 或 JSON 字串）。",
        },
    },
    "manage_scriptable_object": {
        "description": "建立與修改使用 Unity SerializedObject property path 的 ScriptableObject Asset。",
        "title": "管理 ScriptableObject",
        "params": {
            "action": "要執行的動作：create 或 modify。",
            "type_name": "命名空間限定的 ScriptableObject 型別名稱（create 用）。",
            "folder_path": "Assets/... 底下的目標資料夾（create 用）。",
            "asset_name": "不含副檔名的 Asset 檔案名稱（create 用）。",
            "overwrite": "若為 true，覆寫相同路徑既有 Asset（create 用）。",
            "target": "目標 Asset 參照 {guid|path}（modify 用）。",
            "patches": (
                "要套用的 patch 清單（或 JSON 字串）。物件參照使用 "
                "{\"ref\": {\"guid\": \"...\"}} 或 {\"value\": {\"guid\": \"...\"}}。"
                "Sprite 子 Asset：在 ref/value object 中包含 \"spriteName\"。"
                "單一 Sprite texture 只靠 guid/path 也會自動解析。"
            ),
            "dry_run": "若為 true，只驗證 patches 而不套用（僅限 modify）。",
        },
    },
    "manage_tools": {
        "description": (
            "管理此 session 中哪些 tool group 可見。動作：list_groups（顯示所有 group 與狀態）、"
            "activate（啟用 group）、deactivate（停用 group）、sync（從 Unity Editor 的切換狀態重新整理可見性）、"
            "reset（還原預設值）。啟用 group 會讓其 tools 出現；停用則隱藏。"
            "於 Unity Editor GUI 切換 tools 後請使用 sync。"
        ),
        "title": "管理工具",
        "params": {
            "action": "要執行的動作。",
            "group": "群組名稱（activate / deactivate 必填）。有效群組請參考 TOOL_GROUPS。",
        },
    },
    "batch_execute": {
        "description": (
            "批次在單一 batch 中執行多個 MCP 命令，以大幅提升效能。"
            "建立/修改多個 objects、將 Component 加到多個 targets，或執行任何重複操作時強烈建議使用。"
            "相較於連續 tool calls，可降低延遲與 token 成本 10-100x。"
            "每個 batch 的最大命令數可在 Unity MCP Tools 視窗設定（預設 25，硬性上限 100）。"
            "範例：建立 5 個 cubes 時，使用 1 次 batch_execute 搭配 5 個 create commands，"
            "而不是 5 次分開呼叫。"
        ),
        "title": "批次執行",
        "params": {
            "commands": "包含 'tool' 與 'params' key 的命令清單。",
            "parallel": "嘗試平行執行唯讀命令。",
            "fail_fast": "第一次失敗後停止處理。",
            "max_parallelism": "最大平行 worker 數量提示。",
        },
    },
    "execute_menu_item": {
        "description": "執行指定路徑的 Unity menu item。",
        "title": "執行 menu item",
        "params": {
            "menu_path": "用於 'execute' 或 'exists' 的 menu item 路徑（例如 'File/Save Project'）。",
        },
    },
    "execute_custom_tool": {
        "description": "執行 Unity 註冊的專案範圍 Custom Tool。",
        "title": "執行 Custom Tool",
        "params": {},
    },
    "execute_code": {
        "description": (
            "執行 Unity Editor 內的任意 C# 程式碼。"
            "此程式碼會以 method body 執行，並可存取 UnityEngine 與 UnityEditor namespaces。"
            "使用 'return' 回傳資料。在記憶體中編譯，不會建立 script 檔案。"
            "動作：execute（執行程式碼）、get_history（列出過去執行紀錄）、"
            "replay（重新執行 history entry）、clear_history。"
            "注意：safety_checks 會封鎖已知危險 pattern，但不是完整 sandbox。"
            "compiler 選項：'auto'（有 Roslyn 時使用 Roslyn，否則使用 CodeDom）、"
            "'roslyn'（C# 12+，需要 Microsoft.CodeAnalysis）、'codedom'（僅 C# 6）。"
        ),
        "title": "執行程式碼",
        "params": {
            "action": "要執行的動作。",
            "code": (
                "要執行的 C# 程式碼（用於 'execute' action）。必須是有效的 method body。"
                "可存取 UnityEngine 與 UnityEditor namespaces。使用 'return' 回傳資料。"
            ),
            "safety_checks": (
                "啟用基本 blocked-pattern 檢查（File.Delete、Process.Start、infinite loops 等）。"
                "不是完整 sandbox；仍可能進階繞過。預設：true。"
            ),
            "index": "要重播的歷史紀錄索引（用於 'replay' action）。",
            "limit": "要回傳的歷史紀錄筆數（用於 'get_history' action，1-50）。預設：10。",
            "compiler": (
                "用於 'execute' action 的 compiler backend。"
                "'auto' 會在已安裝 Microsoft.CodeAnalysis 時使用 Roslyn，否則 fallback 到 CodeDom。"
                "'roslyn' 強制使用 Roslyn（C# 12+）。"
                "'codedom' 強制使用舊版 CSharpCodeProvider（C# 6）。預設：auto。"
            ),
        },
    },
    "refresh_unity": {
        "description": "重新整理 Unity Asset database，並可選擇要求 script 編譯。也可以等待 Editor 就緒。",
        "title": "重新整理 Unity",
        "params": {
            "mode": "重新整理模式。",
            "scope": "重新整理範圍。",
            "compile": "是否要求編譯。",
            "wait_for_ready": "若為 true，等待 editor_state.advice.ready_for_tools 變成 true。",
        },
    },
    "debug_request_context": {
        "description": "回傳目前 FastMCP request context 詳細資訊（client_id、session_id 與 meta dump）。",
        "title": "除錯 request context",
        "params": {},
    },
}
